# Navigation links to be displayed in the header
navigation:
  - text: Home
    url: /
  - text: Documentation
    url: /docs
  - text: Examples
    url: /examples
  - text: GitHub
    url: https://github.com/intellicode/mdserve