# Navigation links to be displayed in the header
navigation:
  - text: Home
    url: /
  - text: Documentation
    url: /docs
  - text: Examples
    url: /examples
  - text: GitHub
    url: https://github.com/intellicode/mdserve

# Source directory for markdown files (default is current directory)
source_dir: "./examples"

# Template directory for HTML templates (default is "./templates")
template_dir: "./templates"